model: "EleutherAI/gpt-neo-2.7B"
batch_size: 4
dataset: "gpt3mix/sst2"
ice_num: 8
split: "test"
input_column: "text"
output_column: "label"
template: "Movie Review:{text}\nSentiment:{verb}"
label_map:
  0: "positive"
  1: "negative"
